apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    type: web
    app: backend
spec:
  selector:
    matchLabels:
      type: web
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        type: web
        app: backend
        version: v16
    spec:
      containers:
      - name: backend
        image: seonyoung1227/backend:16
        envFrom:
          - configMapRef:
              name: mysql-cm
          - secretRef:
              name: mysql-sec
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m